Script started on Sun 22 Feb 2015 11:59:47 PM PST
]0;shawnjzlee@ubuntu: ~/Desktop/Dropbox/CS100-shawnjzlee@ubuntu:~/Desktop/Dropbox/CS100$ exitbin/rshell #now testing rshell for IO manipulation[4Pvalgrind bin/rshell #checking for memory leaks[4P[C[4@cppcheck rshell.cpp[C[Cexit[Kcppcheck rshell.cppexit[Kcppcheck rshell.cppexit[Kcppcheck rshell.cpp #checking for memory leaks
Checking rshell.cpp...
]0;shawnjzlee@ubuntu: ~/Desktop/Dropbox/CS100-shawnjzlee@ubuntu:~/Desktop/Dropbox/CS100$ cppcheck rshell.cpp #checking for memory leaks[Cexit[Kbin/rshell #now testing rshell for IO manipulation[4Pvalgrind bin/rshell #checking for memory leaks
==3974== Memcheck, a memory error detector
==3974== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==3974== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==3974== Command: bin/rshell
==3974== 
getlogin(): no information received: No such file or directory
ubuntu@ubuntu$ echo helloworld > test.test
ubuntu@ubuntu$ echo helloworld  eag   agia  ain >> test.test
ubuntu@ubuntu$ exit
==3974== 
==3974== HEAP SUMMARY:
==3974==     in use at exit: 58 bytes in 2 blocks
==3974==   total heap usage: 87 allocs, 85 frees, 10,357 bytes allocated
==3974== 
==3974== LEAK SUMMARY:
==3974==    definitely lost: 0 bytes in 0 blocks
==3974==    indirectly lost: 0 bytes in 0 blocks
==3974==      possibly lost: 58 bytes in 2 blocks
==3974==    still reachable: 0 bytes in 0 blocks
==3974==         suppressed: 0 bytes in 0 blocks
==3974== Rerun with --leak-check=full to see details of leaked memory
==3974== 
==3974== For counts of detected and suppressed errors, rerun with: -v
==3974== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;shawnjzlee@ubuntu: ~/Desktop/Dropbox/CS100-shawnjzlee@ubuntu:~/Desktop/Dropbox/CS100$ valgrind bin/rshell #checking for memory leaks[Ccppcheck rshell.cpp[C[Cexit[Kbin/rshell #now testing rshell for IO manipulation[4Pvalgrind bin/rshell #checking for memory leaks[Cbin/rshell #now testing rshell for IO manipulation
getlogin(): no information received: No such file or directory
ubuntu@ubuntu$ echo helloworld > test.test #testing redirect
ubuntu@ubuntu$ ech   cat < test.test #testing redirect and checking file for information in text
helloworld
ubuntu@ubuntu$ echo helloworldagain>test.test #testing redirect without spaces in between
helloworldagain>test.test
ubuntu@ubuntu$ echo helloworldagain >> test.test #testing redirect with existing file and appending new text
ubuntu@ubuntu$ cat < test.test #testing redirect and checking file for text after appending new text
helloworld
helloworldagain
ubuntu@ubuntu$ cat<test.test #checking file for information in text (without spaces)(does not work)
ubuntu@ubuntu$ echo hello world | grep hello #testing piping with grep (word exists)
hello world
ubuntu@ubuntu$ echo hello world | grep exist #testing piping with grep (word doesn't exist)(does not work)
hello world
ubuntu@ubuntu$ exit    #this concludes the test
ubuntu@ubuntu$ exit
]0;shawnjzlee@ubuntu: ~/Desktop/Dropbox/CS100-shawnjzlee@ubuntu:~/Desktop/Dropbox/CS100$ exit
exit

Script done on Mon 23 Feb 2015 12:03:23 AM PST
